---
title: "exports_ADUANA"
author: "Camila Vargas e Ignacia Rivera"
date: "2 de noviembre de 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This document cleans the Aduana dataset maatching species with the aduana code from XXXX


Data was downloaded from XXX on October 8 2018.

Here the [link](http://www.aduana.cl/aduana/site/artic/20080218/pags/20080218165942.html#vtxt_cuerpo_T47) witht the details of the codes use in the esports datasets

## Setup
```{r}
library(tidyverse)
library(here)
library(readxl)
library(stringr)
library(purrr) ##install.packages("purrr")
```



## Import aduana export data

```{r}

## Create a list of files to be read

export_list <- list.files(here('information/raw_databases/ADUANAS_CHILE/exports'), pattern= 'exports_20.*.csv', full.names = TRUE)

export_list <- export_list[4:9]

## Read, wrangle and bind all y datasets
exports_all <- export_list %>% 
  map(read_delim,";", escape_double = FALSE, trim_ws = TRUE, col_names = FALSE, skip =1) %>% 
  reduce(rbind) %>% 
  select(X1, X2, X5, X9, X12, X13, X14, X15, X16, X17) %>% 
  rename(year= X1, month = X2, region = X5, destination = X9, item_sa =X12, fob = X13, fub = X14, kg = X15, quantity = X16, unit = X17)
  
## Save the initial "clean raw data"
# write.csv(landings_SERNAPESCA,  here("clean_databases/intermediate/exports_all_ADUANA.csv"), row.names=F)

```

## Data of our interest

```{r}

##sumarise data to get values per year
exports_yr <- exports_all %>% 
  select(- month, -region, - destination, - quantity, -unit, - fub) %>% 
  mutate(fob= as.integer(as.numeric(fob))) %>% 
  mutate(kg= as.numeric(sub(",", ".", kg, fixed = TRUE)))%>% 
  group_by(year, item_sa) %>% 
  summarise(value_fob = mean(fob, na.rm = T),
            tons = mean(kg, na.rm = T)/1000)


###OJO VER PORQUE VALUE FOB TIENE TANTOS NAs!!!
#Warning messages:
#1: In evalq(as.integer(as.numeric(fob)), <environment>) :
 # NAs introducidos por coerci'on
#2: In evalq(as.integer(as.numeric(fob)), <environment>) :
 # NAs introduced by coercion to integer range

```

## match with species SERNAPESCA data base

```{r}
## importa data set

cod_aduana_sp <- read_excel(here("information/raw_databases/ADUANAS_CHILE/arancel_aduanero_nomenclatura/arancel_aduanero_2017/codigos_aduana_por_especie_2017.xlsx"), sheet = "Hoja1", range = "A1:G703") %>%
mutate(item_sa = gsub("[.]","",codigo_aduana))


##eliminar espacio previo a la especie
##hay alguna forma e leer acentos??

```

```{r}
## maching segun codigo aduanero

match_exports <- exports_yr %>% 
  left_join(cod_aduana_sp, by = "item_sa") %>% 
  filter(!is.na(especie_SERNAPESCA))


```






